Docsite pr label
ansible/ansibullbot pull request #1537
Opened 2021-03-24 23:15 UTC by sommersoft

Addresses item two for #1193.

This will apply the `docsite_pr` to pull requests that have been edited on GitHub, using the "Edit On GitHub" feature. Commits made via this feature carry a couple specific metadata items (see attachment).

I got lucky and there was an open PR on `ansible/ansible` that used this feature:
```shell
$ ./triage_ansible.py --dry-run --verbose --pr 74006 --logfile ../ansibot_log/log.txt --ignore_galaxy
2021-03-24 17:46:45,070 INFO 2938 ansible.py:__init__:225 starting bot
....
2021-03-24 17:46:57,657 INFO 2938 ansible.py:run:506 url: https://github.com/ansible/ansible/pull/74006
2021-03-24 17:46:57,657 INFO 2938 ansible.py:run:507 title: docs(#73995): fix broken link in doc
2021-03-24 17:46:57,657 INFO 2938 ansible.py:run:510 component[f]: lib/ansible/modules/user.py
2021-03-24 17:46:57,657 INFO 2938 ansible.py:run:523 needs_revision
{'cancel_ci': False,
 'cancel_ci_branch': False,
 'close': False,
 'close_migrated': False,
 'comments': [],
 'merge': False,
 'newlabel': ['docsite_pr', 'needs_ci', 'needs_revision'],
 'open': False,
 'rebuild': False,
 'rebuild_failed': False,
 'uncomment': [],
 'unlabel': ['core_review']}
Dry-run specified, skipping execution of actions
2021-03-24 17:46:57,657 INFO 2938 ansible.py:run:540 finished triage for https://github.com/ansible/ansible/pull/74006 in 9.247569s
2021-03-24 17:46:57,657 INFO 2938 ansible.py:run:544 triaged 1 issues in 9.982991 seconds
2021-03-24 17:46:57,657 INFO 2938 defaulttriager.py:start:148 stopping bot
```

_Full run log and GitHub API response:_ [docsite_pr_example.txt](https://github.com/ansible/ansibullbot/files/6200980/docsite_pr_example.txt)

Tagging @acozine

2021-03-26 14:53 UTC, mkrizek commented
Thanks!

> I got lucky and there was an open PR on ansible/ansible that used this feature:

You could have also created a PR (via `Edit on Github` link) and indicate in the PR description that it is to test the bot.

Just a note, another way to determine whether to use the `docsite_pr` label would be to scan the description for `+label: docsite_pr` which is what is added (unless the submitter removes it...) automatically as a part of the PR template. We could get that "for free" if we implemented https://github.com/ansible/ansibullbot/issues/1003.

I am fine with this. Anything to add from the docs team side, @acozine ?

2021-03-26 14:59 UTC, mkrizek requested changes
It appears that there is a false positive for this PR https://github.com/ansible/ansible/pull/73939. Sounds like we should include a unit test for a case where the label should not be applied?

2021-03-29 00:24 UTC, sommersoft commented
> Just a note, another way to determine whether to use the `docsite_pr` label would be to scan the description for `+label: docsite_pr` which is what is added (unless the submitter removes it...) automatically as a part of the PR template. We could get that "for free" if we implemented #1003.

I _thought_ this was already working. This brings up an intent question, I guess (more on that later). I might go ahead and make a new PR on `ansible/ansible` for testing/verification.

> It appears that there is a false positive for this PR ansible/ansible#73939.

The second commit in that PR was done via `Edit on GitHub` ([API link](https://api.github.com/repos/ansible/ansible/commits/b0f80a57eaa488b1b55c70ab56575e70dc335d9d)). This was likely direct-from-github.com, as opposed to being from docs.ansible.com. 

 
The two things above drive a question of intent, for me. Is the desire to label/gather metrics for `docsite_pr`:
1. Only from docs.ansible.com? 
2. Wider use, including both docs.ansible.com and direct-from-github.com?

@acozine and the DaWGs would need to answer this. Might be best to bring it up as an agenda item in a DaWGs meeting?

If the answer is item 1, then `+label: docsite_pr` would be the best way and this PR can be closed.

-----

> Sounds like we should include a unit test for a case where the label should not be applied?

Easy enough to just add another parametrized item.

2021-03-29 06:59 UTC, mkrizek commented
> The two things above drive a question of intent, for me. Is the desire to label/gather metrics for `docsite_pr`:
> 
> 1. Only from docs.ansible.com?
> 2. Wider use, including both docs.ansible.com and direct-from-github.com?
> 
> @acozine and the DaWGs would need to answer this. Might be best to bring it up as an agenda item in a DaWGs meeting?

Yes, thanks!

2024-05-20 16:46 UTC, mkrizek commented
I am going to close this PR as this project is no longer active and will be marked as read-only soon. Thank you for your contribution @sommersoft!

2024-05-20 16:46 UTC, closed without merging